version: 2.1

orbs:
  base: dialogue/base@1.9.1
  release: dialogue/release@2.1.7
  python: dialogue/python@2.11.1

aliases:
  - &executor
    executor:
      name: python/python
      version: "3.9"

workflows:
  ci:
    jobs:
      - python/black:
          name: black
          <<: *executor
          context: org-global-v2
      - python/isort:
          name: isort
          <<: *executor
          context: org-global-v2
      - python/pylama:
          name: pylama
          <<: *executor
          context: org-global-v2
      - python/test:
          name: test
          <<: *executor
          context: org-global-v2
      - release/release:
          name: release
          requires:
            - black
            - pylama
            - isort
            - test
          context: org-global-v2
          filters:
            branches:
              only: master
  release:
    jobs:
      - publish:
          name: publish
          context: org-global-v2
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  publish:
    docker:
    - image: cimg/python:3.9
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_ACCESS_TOKEN
    working_directory: ~/project/.
    steps:
      - base/setup
      - python/setup
      - run:
          name: "publish package on pypi"
          command: |
            poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
            poetry publish --build --no-interaction
